<?php
namespace Burzum\Imagine\Lib;

use Cake\Core\InstanceConfigTrait;
use \Imagine\Image\ImageInterface;
use \Imagine\Image\Point;
use \Imagine\Image\Box;

class ImageProcessor {

	use InstanceConfigTrait;

/**
 * Default settings
 *
 * @var array
 */
	protected $_defaultConfig = [
		'engine' => 'Gd'
	];

/**
 * Imagine Engine Instance
 *
 * @var Object
 */
	protected $_imagine = null;

/**
 * Image object instace
 *
 * @var Object
 */
	protected $_image = null;

/**
 * Constructor
 *
 * @var array $config
 */
	public function __construct(array $config = []) {
		$this->config($config);
	}

/**
 * Get the imagine object
 *
 * @return Imagine object
 */
	public function imagine($renew = false) {
		if (empty($this->_imagine) || $renew === true) {
			$class = '\Imagine\\' . $this->config('engine') . '\Imagine';
			$this->_imagine = new $class();
			return $this->_imagine;
		}
		return $this->_imagine;
	}

/**
 *
 */
	public function open($image) {
		if (!file_exists($image)) {
			throw new \RuntimeException(sprintf('File %s does not exist!', $image));
		}
		$this->_image = $this->imagine()->open($image);
		return $this->_image;
	}

/**
 * Loads an image and applies operations on it
 *
 * Caching and taking care of the file storage is NOT the purpose of this method!
 *
 * @param $ImageObject
 * @param null $output
 * @param array $imagineOptions
 * @param array $operations
 * @throws \BadMethodCallException
 * @internal param string $image source image path
 * @internal param $mixed
 * @internal param \Imagine $array image objects save() 2nd parameter options
 * @return boolean
 */
	public function processImage($ImageObject, $output = null, $imagineOptions = array(), $operations = array()) {
		if (is_string($ImageObject)) {
			$ImageObject = $this->imagine()->open($ImageObject);
		}

		foreach ($operations as $operation => $params) {
			if (method_exists($this->_table, $operation)) {
				$this->_table->{$operation}($ImageObject, $params);
			} elseif (method_exists($this, $operation)) {
				$this->{$operation}($ImageObject, $params);
			} else {
				throw new \BadMethodCallException(__d('imagine', 'Unsupported image operation %s!', $operation));
			}
		}

		if (is_null($output)) {
			return $ImageObject;
		}

		$ImageObject->save($output, $imagineOptions);
		$this->_image = null;
		return $this;
	}

/**
 * Turns the operations and their params into a string that can be used in a file name to cache an image.
 *
 * Suffix your image with the string generated by this method to be able to batch delete a file that has versions of it cached.
 * The intended usage of this is to store the files as my_horse.thumbnail+width-100-height+100.jpg for example.
 *
 * So after upload store your image meta data in a db, give the filename the id of the record and suffix it
 * with this string and store the string also in the db. In the views, if no further control over the image access is needd,
 * you can simply direct linke the image like $this->Html->image('/images/05/04/61/my_horse.thumbnail+width-100-height+100.jpg');
 *
 * @param array $operations Imagine image operations
 * @param array $separators Optional
 * @param bool $hash
 * @return string Filename compatible String representation of the operations
 * @link http://support.microsoft.com/kb/177506
 */
	public function operationsToString($operations, $separators = array(), $hash = false) {
		return ImagineUtility::operationsToString($operations, $separators, $hash);
	}

/**
 * hashImageOperations
 *
 * @param array $imageSizes
 * @param int $hashLenght
 * @return string
 */
	public function hashImageOperations($imageSizes, $hashLenght = 8) {
		return ImagineUtility::hashImageOperations($imageSizes, $hashLenght = 8);
	}

/**
 * Wrapper for Imagines crop
 *
 * @param $Image
 * @param array Array of options for processing the image
 * @throws \InvalidArgumentException
 * @return void
 */
	public function crop($Image, $options = array()) {
		if (empty($options['height']) || empty($options['width'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You have to pass height and width in the options!'));
		}

		$defaults = [
			'cropX' => 0,
			'cropY' => 0
		];

		$options = array_merge($defaults, $options);

		$Image->crop(new \Imagine\Image\Point($options['cropX'], $options['cropY']), new \Imagine\Image\Box($options['width'], $options['height']));
	}

/**
 * Crops an image based on its widht or height, crops it to a square and resizes it to the given size
 *
 * @param $Image
 * @param array Array of options for processing the image
 * @throws \InvalidArgumentException
 * @return void
 */
	public function squareCenterCrop($Image, array $options = array()) {
		if (empty($options['size'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You have to pass size in the options!'));
		}

		$imageSize = $this->getImageSize($Image);

		$width = $imageSize[0];
		$height = $imageSize[1];

		if ($width > $height) {
			$x2 = $height;
			$y2 = $height;
			$x = ($width - $height) / 2;
			$y = 0;
		} else {
			$x2 = $width;
			$y2 = $width;
			$x = 0;
			$y = ($height - $width) / 2;
		}

		$Image->crop(new \Imagine\Image\Point($x, $y), new \Imagine\Image\Box($x2, $y2));
		$Image->resize(new \Imagine\Image\Box($options['size'], $options['size']));
	}

/**
 * Widen
 *
 * @param $Image
 * @param array $options
 * @throws \InvalidArgumentException
 * @return void
 */
	public function widen($Image, array $options = array()) {
		if (empty($options['size'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You must pass a size value!'));
		}
		$this->widenAndHeighten($Image, array('width' => $options['size']));
	}

/**
 * Heighten
 *
 * @param $Image
 * @param array $options
 * @throws \InvalidArgumentException
 * @return void
 */
	public function heighten($Image, array $options = array()) {
		if (empty($options['size'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You must pass a size value!'));
		}
		$this->widenAndHeighten($Image, array('height' => $options['size']));
	}

/**
 * WidenAndHeighten
 *
 * @param $Image
 * @param array $options
 * @throws \InvalidArgumentException
 * @return void
 */
	public function widenAndHeighten($Image, $options = array()) {
		if (empty($options['height']) && empty($options['width']) && empty($options['size'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You have to pass a height, width or size!'));
		}

		if (!empty($options['height']) && !empty($options['width'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You can only scale by width or height!'));
		}

		if (isset($options['width'])) {
			$size = $options['width'];
			$method = 'widen';
		} elseif (isset($options['height'])) {
			$size = $options['height'];
			$method = 'heighten';
		} else {
			$size = $options['size'];
			$method = 'scale';
		}

		$imageSize = $this->getImageSize($Image);
		$width = $imageSize[0];
		$height = $imageSize[1];

		if (isset($options['noUpScale'])) {
			if ($method == 'widen') {
				if ($size > $width) {
					throw new \InvalidArgumentException(__d('Imagine', 'You can not scale up!'));
				}
			} elseif ('heighten') {
				if ($size > $height) {
					throw new \InvalidArgumentException(__d('Imagine', 'You can not scale up!'));
				}
			}
		}

		if (isset($options['noDownScale'])) {
			if ($method == 'widen') {
				if ($size < $width) {
					throw new \InvalidArgumentException(__d('Imagine', 'You can not scale down!'));
				}
			} elseif ('heighten') {
				if ($size < $height) {
					throw new \InvalidArgumentException(__d('Imagine', 'You can not scale down!'));
				}
			}
		}

		$Box = new \Imagine\Image\Box($width, $height);
		$Box = $Box->{$method}($size);
		$Image->resize($Box);
	}

/**
 * Heighten
 *
 * @param $Image
 * @param array $options
 * @throws \InvalidArgumentException
 * @return void
 */
	public function scale($Image, $options = array()) {
		if (empty($options['factor'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You must pass a factor value!'));
		}

		$imageSize = $this->getImageSize($Image);
		$width = $imageSize[0];
		$height = $imageSize[1];

		$Box = new \Imagine\Image\Box($width, $height);
		$Box = $Box->scale($options['factor']);
		return $Image->resize($Box);
	}

/**
 * Wrapper for Imagine flipHorizontally and flipVertically
 *
 * @param $Image
 * @param array Array of options for processing the image
 * @throws \InvalidArgumentException
 * @return void
 */
	public function flip($Image, $options = array()) {
		if (!isset($options['direction'])) {
			$options['direction'] = 'vertically';
		}
		if (!in_array($options['direction'], array('vertically', 'horizontall'))) {
			throw new \InvalidArgumentException(__d('Imagine', 'Invalid direction, use verticall or horizontall'));
		}
		$method = 'flip' . $options['direction'];
		return $Image->{$method}();
	}

/**
 * Wrapper for rotate
 *
 * @param object Imagine Image Object
 * @param array Array of options for processing the image
 */
	public function rotate($Image, array $options = array()) {
		$this->_image = $Image->rotate($options['degree']);
		return $this;
	}

/**
 * Wrapper for Imagines thumbnail.
 *
 * @throws \InvalidArgumentException
 * @param Imagine Image Object
 * @param array Array of options for processing the image
 * @throws InvalidArgumentException if no height or width was passed
 * @return void
 */
	public function thumbnail(&$Image, array $options = array()) {
		if (empty($options['height']) || empty($options['width'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You have to pass height and width in the options!'));
		}

		$mode = ImageInterface::THUMBNAIL_INSET;
		if (isset($options['mode']) && $options['mode'] == 'outbound') {
			$mode = ImageInterface::THUMBNAIL_OUTBOUND;
		}

		$this->_image = $Image->thumbnail(new Box($options['width'], $options['height']), $mode);
		return $this;
	}

/**
 * Wrapper for Imagines resize
 *
 * @param $Image
 * @param array Array of options for processing the image
 * @throws \InvalidArgumentException
 * @internal param \Imagine\Imagine $Imagine Image Object
 */
	public function resize($Image, array $options = array()) {
		if (empty($options['height']) || empty($options['width'])) {
			throw new \InvalidArgumentException(__d('Imagine', 'You have to pass height and width in the options!'));
		}

		$this->_image = $Image->resize(new Box($options['width'], $options['height']));
		return $this;
	}

	public function autoRotate() {

	}

/**
 * Gets the size of an image
 *
 * @param mixed Imagine Image object or string of a file name
 * @return array first value is width, second height
 * @see Imagine\Image\ImageInterface::getSize()
 */
	public function getImageSize($Image = null) {
		if (is_string($Image)) {
			$class = 'Imagine\\' . $this->settings['engine'] . '\Imagine';
			$Imagine = new $class();
			$Image = $Imagine->open($Image);
		}
		if (!empty($this->_image)) {
			$Image = $this->_image;
		}

		$BoxInterface = $Image->getSize($Image);

		return array(
			$BoxInterface->getWidth(),
			$BoxInterface->getHeight(),
			'x' => $BoxInterface->getWidth(),
			'y' => $BoxInterface->getHeight()
		);
	}
}
